services:
  postgres:
    image: postgres:16-alpine
    container_name: veylix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: veylix_user
      POSTGRES_PASSWORD: veylix_secret_pass
      POSTGRES_DB: veylix_db
    ports:
      - "5433:5432"
    volumes:
      - veylix_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U veylix_user -d veylix_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  veylix_pgdata:
    driver: local
